AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Baseline Lambda Nodejs"
Resources:
  BaselineLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BaselineLambda
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout : 60
      CodeUri: .